[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build", "-r"]
dependencies = ["clean"]

[tasks.my-task]
dependencies = [
    "format",
    "clean",
    "build"
]